<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/afectacion.php');
	include_once(__DIR__ . '/afectacion_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('afectacion');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'afectacion';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`afectacion`.`VcrIdAfe`" => "VcrIdAfe",
		"`afectacion`.`VcrAfe`" => "VcrAfe",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`afectacion`.`VcrIdAfe`" => "VcrIdAfe",
		"`afectacion`.`VcrAfe`" => "VcrAfe",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`afectacion`.`VcrIdAfe`" => "CODIGO TIPO AFECTACION",
		"`afectacion`.`VcrAfe`" => "NOMBRE TIPO AFECTACION",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`afectacion`.`VcrIdAfe`" => "VcrIdAfe",
		"`afectacion`.`VcrAfe`" => "VcrAfe",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`afectacion` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'afectacion_view.php';
	$x->TableTitle = 'Afectacion';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`afectacion`.`VcrIdAfe`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['CODIGO TIPO AFECTACION', 'NOMBRE TIPO AFECTACION', ];
	$x->ColFieldName = ['VcrIdAfe', 'VcrAfe', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/afectacion_templateTV.html';
	$x->SelectedTemplate = 'templates/afectacion_templateTVS.html';
	$x->TemplateDV = 'templates/afectacion_templateDV.html';
	$x->TemplateDVP = 'templates/afectacion_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: afectacion_init
	$render = true;
	if(function_exists('afectacion_init')) {
		$args = [];
		$render = afectacion_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: afectacion_header
	$headerCode = '';
	if(function_exists('afectacion_header')) {
		$args = [];
		$headerCode = afectacion_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: afectacion_footer
	$footerCode = '';
	if(function_exists('afectacion_footer')) {
		$args = [];
		$footerCode = afectacion_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
