<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/caracteristicas_evento.php');
	include_once(__DIR__ . '/caracteristicas_evento_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('caracteristicas_evento');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'caracteristicas_evento';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`caracteristicas_evento`.`VcrIdCar`" => "VcrIdCar",
		"`caracteristicas_evento`.`VcrCarFen`" => "VcrCarFen",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`caracteristicas_evento`.`VcrIdCar`" => "VcrIdCar",
		"`caracteristicas_evento`.`VcrCarFen`" => "VcrCarFen",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`caracteristicas_evento`.`VcrIdCar`" => "CODIGO DE LA CARACTERISTICA DEL EVENTO",
		"`caracteristicas_evento`.`VcrCarFen`" => "NOMBRE DE LA CARACTERISTICA DEL EVENTO",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`caracteristicas_evento`.`VcrIdCar`" => "VcrIdCar",
		"`caracteristicas_evento`.`VcrCarFen`" => "VcrCarFen",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`caracteristicas_evento` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'caracteristicas_evento_view.php';
	$x->TableTitle = 'Caracteristicas evento';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`caracteristicas_evento`.`VcrIdCar`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['CODIGO DE LA CARACTERISTICA DEL EVENTO', 'NOMBRE DE LA CARACTERISTICA DEL EVENTO', ];
	$x->ColFieldName = ['VcrIdCar', 'VcrCarFen', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/caracteristicas_evento_templateTV.html';
	$x->SelectedTemplate = 'templates/caracteristicas_evento_templateTVS.html';
	$x->TemplateDV = 'templates/caracteristicas_evento_templateDV.html';
	$x->TemplateDVP = 'templates/caracteristicas_evento_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: caracteristicas_evento_init
	$render = true;
	if(function_exists('caracteristicas_evento_init')) {
		$args = [];
		$render = caracteristicas_evento_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: caracteristicas_evento_header
	$headerCode = '';
	if(function_exists('caracteristicas_evento_header')) {
		$args = [];
		$headerCode = caracteristicas_evento_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: caracteristicas_evento_footer
	$footerCode = '';
	if(function_exists('caracteristicas_evento_footer')) {
		$args = [];
		$footerCode = caracteristicas_evento_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
