<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/procesos.php');
	include_once(__DIR__ . '/procesos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('procesos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'procesos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`procesos`.`VcrIdProc`" => "VcrIdProc",
		"`procesos`.`VcrNomProc`" => "VcrNomProc",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`procesos`.`VcrIdProc`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`procesos`.`VcrIdProc`" => "VcrIdProc",
		"`procesos`.`VcrNomProc`" => "VcrNomProc",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`procesos`.`VcrIdProc`" => "Id proceso",
		"`procesos`.`VcrNomProc`" => "Nombre del proceso",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`procesos`.`VcrIdProc`" => "VcrIdProc",
		"`procesos`.`VcrNomProc`" => "VcrNomProc",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`procesos` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'procesos_view.php';
	$x->TableTitle = 'Procesos';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`procesos`.`VcrIdProc`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Id proceso', 'Nombre del proceso', ];
	$x->ColFieldName = ['VcrIdProc', 'VcrNomProc', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/procesos_templateTV.html';
	$x->SelectedTemplate = 'templates/procesos_templateTVS.html';
	$x->TemplateDV = 'templates/procesos_templateDV.html';
	$x->TemplateDVP = 'templates/procesos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: procesos_init
	$render = true;
	if(function_exists('procesos_init')) {
		$args = [];
		$render = procesos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: procesos_header
	$headerCode = '';
	if(function_exists('procesos_header')) {
		$args = [];
		$headerCode = procesos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: procesos_footer
	$footerCode = '';
	if(function_exists('procesos_footer')) {
		$args = [];
		$footerCode = procesos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
