<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/servidor_publico.php');
	include_once(__DIR__ . '/servidor_publico_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('servidor_publico');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'servidor_publico';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`servidor_publico`.`VcrIdSerP`" => "VcrIdSerP",
		"`servidor_publico`.`VcrSerPub`" => "VcrSerPub",
		"`servidor_publico`.`VcrTipSerP`" => "VcrTipSerP",
		"IF(    CHAR_LENGTH(`procesos1`.`VcrNomProc`), CONCAT_WS('',   `procesos1`.`VcrNomProc`), '') /* Proceso asociado */" => "VcrIdProc",
		"`servidor_publico`.`VcrCelSerP`" => "VcrCelSerP",
		"`servidor_publico`.`VcrCorrSerP`" => "VcrCorrSerP",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`servidor_publico`.`VcrIdSerP`',
		2 => 2,
		3 => 3,
		4 => '`procesos1`.`VcrNomProc`',
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`servidor_publico`.`VcrIdSerP`" => "VcrIdSerP",
		"`servidor_publico`.`VcrSerPub`" => "VcrSerPub",
		"`servidor_publico`.`VcrTipSerP`" => "VcrTipSerP",
		"IF(    CHAR_LENGTH(`procesos1`.`VcrNomProc`), CONCAT_WS('',   `procesos1`.`VcrNomProc`), '') /* Proceso asociado */" => "VcrIdProc",
		"`servidor_publico`.`VcrCelSerP`" => "VcrCelSerP",
		"`servidor_publico`.`VcrCorrSerP`" => "VcrCorrSerP",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`servidor_publico`.`VcrIdSerP`" => "DOCUMENTO IDENTIDAD SERVIDOR PUBLICO",
		"`servidor_publico`.`VcrSerPub`" => "NOMBRE SERVIDOR PUBLICO",
		"`servidor_publico`.`VcrTipSerP`" => "Tipo servidor p&#250;blico",
		"IF(    CHAR_LENGTH(`procesos1`.`VcrNomProc`), CONCAT_WS('',   `procesos1`.`VcrNomProc`), '') /* Proceso asociado */" => "Proceso asociado",
		"`servidor_publico`.`VcrCelSerP`" => "Celular servidor p&#250;blico",
		"`servidor_publico`.`VcrCorrSerP`" => "Correo Electr&#243;nico",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`servidor_publico`.`VcrIdSerP`" => "VcrIdSerP",
		"`servidor_publico`.`VcrSerPub`" => "VcrSerPub",
		"`servidor_publico`.`VcrTipSerP`" => "VcrTipSerP",
		"IF(    CHAR_LENGTH(`procesos1`.`VcrNomProc`), CONCAT_WS('',   `procesos1`.`VcrNomProc`), '') /* Proceso asociado */" => "VcrIdProc",
		"`servidor_publico`.`VcrCelSerP`" => "VcrCelSerP",
		"`servidor_publico`.`VcrCorrSerP`" => "VcrCorrSerP",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['VcrIdProc' => 'Proceso asociado', ];

	$x->QueryFrom = "`servidor_publico` LEFT JOIN `procesos` as procesos1 ON `procesos1`.`VcrIdProc`=`servidor_publico`.`VcrIdProc` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'servidor_publico_view.php';
	$x->TableTitle = 'Servidor publico';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`servidor_publico`.`VcrIdSerP`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['DOCUMENTO IDENTIDAD SERVIDOR PUBLICO', 'NOMBRE SERVIDOR PUBLICO', 'Tipo servidor p&#250;blico', 'Proceso asociado', 'Celular servidor p&#250;blico', 'Correo Electr&#243;nico', ];
	$x->ColFieldName = ['VcrIdSerP', 'VcrSerPub', 'VcrTipSerP', 'VcrIdProc', 'VcrCelSerP', 'VcrCorrSerP', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/servidor_publico_templateTV.html';
	$x->SelectedTemplate = 'templates/servidor_publico_templateTVS.html';
	$x->TemplateDV = 'templates/servidor_publico_templateDV.html';
	$x->TemplateDVP = 'templates/servidor_publico_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: servidor_publico_init
	$render = true;
	if(function_exists('servidor_publico_init')) {
		$args = [];
		$render = servidor_publico_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: servidor_publico_header
	$headerCode = '';
	if(function_exists('servidor_publico_header')) {
		$args = [];
		$headerCode = servidor_publico_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: servidor_publico_footer
	$footerCode = '';
	if(function_exists('servidor_publico_footer')) {
		$args = [];
		$footerCode = servidor_publico_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
