<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/solicitudes.php');
	include_once(__DIR__ . '/solicitudes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('solicitudes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'solicitudes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`solicitudes`.`VcrIdSol`" => "VcrIdSol",
		"`solicitudes`.`VcrSol`" => "VcrSol",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`solicitudes`.`VcrIdSol`" => "VcrIdSol",
		"`solicitudes`.`VcrSol`" => "VcrSol",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`solicitudes`.`VcrIdSol`" => "CODIGO TIPO DE SOLICITUD",
		"`solicitudes`.`VcrSol`" => "NOMBRE DEL TIPO DE SOLICITUD",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`solicitudes`.`VcrIdSol`" => "VcrIdSol",
		"`solicitudes`.`VcrSol`" => "VcrSol",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`solicitudes` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'solicitudes_view.php';
	$x->TableTitle = 'Solicitudes';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`solicitudes`.`VcrIdSol`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['CODIGO TIPO DE SOLICITUD', 'NOMBRE DEL TIPO DE SOLICITUD', ];
	$x->ColFieldName = ['VcrIdSol', 'VcrSol', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/solicitudes_templateTV.html';
	$x->SelectedTemplate = 'templates/solicitudes_templateTVS.html';
	$x->TemplateDV = 'templates/solicitudes_templateDV.html';
	$x->TemplateDVP = 'templates/solicitudes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: solicitudes_init
	$render = true;
	if(function_exists('solicitudes_init')) {
		$args = [];
		$render = solicitudes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: solicitudes_header
	$headerCode = '';
	if(function_exists('solicitudes_header')) {
		$args = [];
		$headerCode = solicitudes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: solicitudes_footer
	$footerCode = '';
	if(function_exists('solicitudes_footer')) {
		$args = [];
		$footerCode = solicitudes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
