<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/tipo_material.php');
	include_once(__DIR__ . '/tipo_material_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('tipo_material');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tipo_material';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tipo_material`.`VcrIdMat`" => "VcrIdMat",
		"`tipo_material`.`VcrTipMat`" => "VcrTipMat",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tipo_material`.`VcrIdMat`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tipo_material`.`VcrIdMat`" => "VcrIdMat",
		"`tipo_material`.`VcrTipMat`" => "VcrTipMat",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tipo_material`.`VcrIdMat`" => "CODIGO DEL TIPO DE MATERIAL",
		"`tipo_material`.`VcrTipMat`" => "NOMBRE DEL TIPO DE MATERIAL",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tipo_material`.`VcrIdMat`" => "VcrIdMat",
		"`tipo_material`.`VcrTipMat`" => "VcrTipMat",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`tipo_material` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tipo_material_view.php';
	$x->TableTitle = 'Tipo material';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`tipo_material`.`VcrIdMat`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['NOMBRE DEL TIPO DE MATERIAL', ];
	$x->ColFieldName = ['VcrTipMat', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tipo_material_templateTV.html';
	$x->SelectedTemplate = 'templates/tipo_material_templateTVS.html';
	$x->TemplateDV = 'templates/tipo_material_templateDV.html';
	$x->TemplateDVP = 'templates/tipo_material_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tipo_material_init
	$render = true;
	if(function_exists('tipo_material_init')) {
		$args = [];
		$render = tipo_material_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tipo_material_header
	$headerCode = '';
	if(function_exists('tipo_material_header')) {
		$args = [];
		$headerCode = tipo_material_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tipo_material_footer
	$footerCode = '';
	if(function_exists('tipo_material_footer')) {
		$args = [];
		$footerCode = tipo_material_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
