<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/usuarios.php');
	include_once(__DIR__ . '/usuarios_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('usuarios');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'usuarios';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`usuarios`.`VcrIdUsu`" => "VcrIdUsu",
		"`usuarios`.`VcrNomUsu`" => "VcrNomUsu",
		"`usuarios`.`VcrIdenUsu`" => "VcrIdenUsu",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`usuarios`.`VcrIdUsu`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`usuarios`.`VcrIdUsu`" => "VcrIdUsu",
		"`usuarios`.`VcrNomUsu`" => "VcrNomUsu",
		"`usuarios`.`VcrIdenUsu`" => "VcrIdenUsu",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`usuarios`.`VcrIdUsu`" => "Codigo usuario",
		"`usuarios`.`VcrNomUsu`" => "Nombre usuario",
		"`usuarios`.`VcrIdenUsu`" => "Numero de identificacion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`usuarios`.`VcrIdUsu`" => "VcrIdUsu",
		"`usuarios`.`VcrNomUsu`" => "VcrNomUsu",
		"`usuarios`.`VcrIdenUsu`" => "VcrIdenUsu",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`usuarios` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'usuarios_view.php';
	$x->TableTitle = 'Usuarios';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`usuarios`.`VcrIdUsu`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Codigo usuario', 'Nombre usuario', 'Numero de identificacion', ];
	$x->ColFieldName = ['VcrIdUsu', 'VcrNomUsu', 'VcrIdenUsu', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/usuarios_templateTV.html';
	$x->SelectedTemplate = 'templates/usuarios_templateTVS.html';
	$x->TemplateDV = 'templates/usuarios_templateDV.html';
	$x->TemplateDVP = 'templates/usuarios_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: usuarios_init
	$render = true;
	if(function_exists('usuarios_init')) {
		$args = [];
		$render = usuarios_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: usuarios_header
	$headerCode = '';
	if(function_exists('usuarios_header')) {
		$args = [];
		$headerCode = usuarios_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: usuarios_footer
	$footerCode = '';
	if(function_exists('usuarios_footer')) {
		$args = [];
		$footerCode = usuarios_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
